# Generated by Django 5.2.2 on 2025-06-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinemahall_genre_movie_actors_movie_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='sets',
            new_name='sets_in_row',
        ),
    ]
