# Generated by Django 5.2.2 on 2025-06-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_rename_sets_cinemahall_sets_in_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='sets_in_row',
            new_name='seats_in_row',
        ),
    ]
